### ISSUE TITLE
Great Project - Request for Adding Wechaty Badge

### ISSUE THREAD

**Issue by huan** [xinbenlv/haoshiyou-bot#1]
I just linked your project in Wechaty at: https://github.com/wechaty/wechaty/wiki/PoweredByWechaty

If you could add a Wechaty Badge to your project that should be cool. 

[![Powered by Wechaty](https://img.shields.io/badge/Powered%20By-Wechaty-green.svg)](https://github.com/wechaty/wechaty)

```markdown
[![Powered by Wechaty](https://img.shields.io/badge/Powered%20By-Wechaty-green.svg)](https://github.com/wechaty/wechaty)
```

**Comment by xinbenlv** [comment]
A CL will update the Readme.md. Thank you for letting me know, the badge looks great. I might wanna create one too
