### ISSUE TITLE
angular环境如何搭建的？

### ISSUE THREAD

**Issue by forconz** [xinbenlv/haoshiyou-bot#7]
编译时，会报错：
loopbacksdk/index.ts(43,28): error TS2307: Cannot find module '@angular/http'.
loopbacksdk/index.ts(44,30): error TS2307: Cannot find module '@angular/common'.
loopbacksdk/index.ts(45,47): error TS2307: Cannot find module '@angular/core'.

但是我看package.json中dependencies并没有给定@angular，请教一下，@angular的环境如何搭建的?

@xinbenlv 提供一个小建议，用全新的电脑，下载haoshiyou-bot，然后跑起来试试，没有文档和足够知识储备的话，这个源代码跑起来有点难度。

详细的文档麻烦有空补一下了。

**Comment by forconz** [comment]
Executing task: tsc -p "c:\Users\lenovo\Downloads\haoshiyou-bot-master\haoshiyou-bot-master\tsconfig.json" <

loopbacksdk/index.ts(43,28): error TS2307: Cannot find module '@angular/http'.
loopbacksdk/index.ts(44,30): error TS2307: Cannot find module '@angular/common'.
loopbacksdk/index.ts(45,47): error TS2307: Cannot find module '@angular/core'.
loopbacksdk/index.ts(68,14): error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
loopbacksdk/services/core/auth.service.ts(3,36): error TS2307: Cannot find module '@angular/core'.
loopbacksdk/services/core/auth.service.ts(16,14): error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
loopbacksdk/services/core/auth.service.ts(31,15): error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
loopbacksdk/services/core/base.service.ts(2,46): error TS2307: Cannot find module '@angular/core'.
loopbacksdk/services/core/base.service.ts(3,56): error TS2307: Cannot find module '@angular/http'.
loopbacksdk/services/core/base.service.ts(4,47): error TS2307: Cannot find module '@angular/core'.
loopbacksdk/services/core/base.service.ts(30,23): error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
loopbacksdk/services/core/base.service.ts(36,5): error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
loopbacksdk/services/core/base.service.ts(37,5): error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
loopbacksdk/services/core/base.service.ts(38,5): error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
loopbacksdk/services/core/base.service.ts(39,5): error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
loopbacksdk/services/core/base.service.ts(40,5): error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
loopbacksdk/services/core/error.service.ts(2,28): error TS2307: Cannot find module '@angular/core'.
loopbacksdk/services/core/error.service.ts(3,26): error TS2307: Cannot find module '@angular/http'.
loopbacksdk/services/core/error.service.ts(11,14): error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
loopbacksdk/services/core/search.params.ts(2,28): error TS2307: Cannot find module '@angular/core'.
loopbacksdk/services/core/search.params.ts(3,33): error TS2307: Cannot find module '@angular/http'.
loopbacksdk/services/core/search.params.ts(14,14): error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
loopbacksdk/services/custom/HsyInteraction.ts(2,46): error TS2307: Cannot find module '@angular/core'.
loopbacksdk/services/custom/HsyInteraction.ts(3,32): error TS2307: Cannot find module '@angular/http'.
loopbacksdk/services/custom/HsyInteraction.ts(20,14): error TS1219: Experimental support for decorators is a feature that is subject to change in
a future release. Set the 'experimentalDecorators' option to remove this warning.
loopbacksdk/services/custom/HsyInteraction.ts(23,5): error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
loopbacksdk/services/custom/HsyInteraction.ts(24,5): error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
loopbacksdk/services/custom/HsyInteraction.ts(25,5): error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
loopbacksdk/services/custom/HsyInteraction.ts(26,5): error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
loopbacksdk/services/custom/HsyInteraction.ts(27,5): error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
loopbacksdk/services/custom/HsyListing.ts(2,46): error TS2307: Cannot find module '@angular/core'.
loopbacksdk/services/custom/HsyListing.ts(3,32): error TS2307: Cannot find module '@angular/http'.
loopbacksdk/services/custom/HsyListing.ts(21,14): error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
loopbacksdk/services/custom/HsyListing.ts(24,5): error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
loopbacksdk/services/custom/HsyListing.ts(25,5): error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
loopbacksdk/services/custom/HsyListing.ts(26,5): error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
loopbacksdk/services/custom/HsyListing.ts(27,5): error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
loopbacksdk/services/custom/HsyListing.ts(28,5): error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
loopbacksdk/services/custom/HsyUser.ts(2,46): error TS2307: Cannot find module '@angular/core'.
loopbacksdk/services/custom/HsyUser.ts(3,32): error TS2307: Cannot find module '@angular/http'.
loopbacksdk/services/custom/HsyUser.ts(20,14): error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
loopbacksdk/services/custom/HsyUser.ts(23,5): error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
loopbacksdk/services/custom/HsyUser.ts(24,5): error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
loopbacksdk/services/custom/HsyUser.ts(25,5): error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
loopbacksdk/services/custom/HsyUser.ts(26,5): error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
loopbacksdk/services/custom/HsyUser.ts(27,5): error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
loopbacksdk/services/custom/SDKModels.ts(2,28): error TS2307: Cannot find module '@angular/core'.
loopbacksdk/services/custom/SDKModels.ts(10,14): error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
loopbacksdk/services/custom/logger.service.ts(2,28): error TS2307: Cannot find module '@angular/core'.
loopbacksdk/services/custom/logger.service.ts(12,14): error TS1219: Experimental support for decorators is a feature that is subject to change in
a future release. Set the 'experimentalDecorators' option to remove this warning.
loopbacksdk/storage/cookie.browser.ts(2,28): error TS2307: Cannot find module '@angular/core'.
loopbacksdk/storage/cookie.browser.ts(13,14): error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
loopbacksdk/storage/storage.browser.ts(2,28): error TS2307: Cannot find module '@angular/core'.
loopbacksdk/storage/storage.browser.ts(12,14): error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
通过退出代码 1 终止的终端进程

**Comment by forconz** [comment]
loopbacksdk/index.ts(43,28): error TS2307: Cannot find module 'angular/http'.
loopbacksdk/index.ts(44,30): error TS2307: Cannot find module 'angular/common'.
loopbacksdk/index.ts(45,47): error TS2307: Cannot find module 'angular/core'.

angular前面有**@**字符

**Comment by forconz** [comment]
cnpm install angular/core
cnpm install zone.js@^0.8.4
cnpm install angular/common
cnpm install angular/http

angular前面要加个@字符

我发现我用npm install总会出错，用cnpm就好了，估计有什么代码被墙了。

**Comment by xinbenlv** [comment]
This project doesnt directly depend on angular

The failure is due to not having loopbacksdk

You will need to create loopback sdk for typescript and use it here
https://github.com/mean-expert-official/loopback-sdk-builder

sorry bear with my Chinese input keep crashing so i am relying in English

Good luck

Xinbenlv

**Comment by forconz** [comment]
error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.

打开tsconfig.json，compilerOptions下加上配置：
"experimentalDecorators": true,
这个问题就修复了。

**Comment by forconz** [comment]
@xinbenlv Many thanks , I can read your reply, but my english is limit, sorry I posted the issue by chinese.

btw: docker run -ti --volume="$(pwd)":/bot --rm zixia/wechaty src/main.ts
I exec this command, power shell Pulling from zixia/wechaty, but it is too slowly!

Unable to find image 'zixia/wechaty:latest' locally
latest: Pulling from zixia/wechaty
0bd639347642: Downloading [===================================>               ]  27.84MB/39.46MB
     ]  27.84MB/39.46MB
0bd639347642: Pull complete
15f827925d02: Pull complete
8d4e9883d6b5: Pull complete
c754e879539b: Pull complete
85f5abd03ce7: Pull complete0fd536033837: Downloading [=========================>                         ]  102.2MB/202.4MB
581571cc0ba1: Download complete04b6aebfcc37: Download complete
664ca478e2e2: Download complete
1de4acfe0b5e: Download complete
089a14c91c61: Download complete
1bef34743534: Downloading  18.37MB
29c950aa083d: Download complete
281b8237e798: Download complete
1fcf03150b97: Download complete

I exec the command 'docker run -ti --volume="$(pwd)":/bot --rm zixia/wechaty src/main.ts' an hour ago
but it is still Pulling from zixia/wechaty, I get crashing~

**Comment by forconz** [comment]
@xinbenlv another question:

PS D:\robot> cnpm i puppeteer
√ Installed 1 packages
√ Linked 21 latest versions
Downloading Chromium r515411 - 117 Mb [====================] 100% 0.0s
Chromium downloaded to D:\robot\node_modules\_puppeteer@0.13.0@puppeteer\.local-chromiu
m\win64-515411
√ Run 1 scripts
√ All packages installed (18 packages installed from npm registry, used 1m, speed 2.78kB/s, json 22(37.11kB), tarball 1
33.27kB)

I downloaded Chromium to _puppeteer, but I get error by ts-node src/main.ts
D:\robot\node_modules\wechaty\node_modules\puppeteer\lib\Launcher.js
console.assert(revisionInfo.downloaded, `Chromium revision is not downloaded. Run "npm install"`);

Chromium revision is not downloaded? How to do?

**Comment by forconz** [comment]
I copy folder '.local-chromium' to D:\robot\node_modules\wechaty\node_modules\puppeteer
but I get Error: ENOENT: no such file or directory, open 'd:\robot\.credentials\haoshiyou-prod-dc95d5f118ae.json'

what it the .credentials\haoshiyou-prod-dc95d5f118ae.json?

**Comment by xinbenlv** [comment]
没问题，我平时能打中文，我就是昨天晚上在被窝里面回复的，搜狗一直抽疯。

**Comment by xinbenlv** [comment]
.credentials\haoshiyou-prod-dc95d5f118ae.json
这是我们的production环境下的密钥信息，所以没有checkin到代码库里面
